version: '3.9'

services:
  web:
    build: .
    container_name: qiurl_web
    env_file: .env
    command: gunicorn -c gunicorn.conf.py app:app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: qiurl_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: qiurl_redis
    restart: always

  nginx:
    image: nginx:alpine
    container_name: qiurl_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  pgdata:
